version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dndjecool
      POSTGRES_DB: tavern_guide
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      tavern_network:
        ipv4_address: 192.168.1.10

  # Nuxt.js Application Service
  nuxt:
    image: patrikborzik/nuxt-app:latest
    container_name: nuxt-app
    ports:
      - "3000:3000"
    networks:
      tavern_network:
        ipv4_address: 192.168.1.11
    depends_on:
      - db

  # AdonisJS Application Service
  adonis:
    image: patrikborzik/adonis-app:latest
    container_name: adonis-app
    ports:
      - "3333:3333"
    networks:
      tavern_network:
        ipv4_address: 192.168.1.12
    depends_on:
      - db

volumes:
  pg_data:

networks:
  tavern_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
